### ISSUE TITLE
Proceso/InformeCaracterizacion/InformacionTecnica

### ISSUE THREAD

**Issue by mausygarcia** [luiscdz/SCV#1]
El sistema no esta permitiendo visualizar los puntos de vetimeintos que se han creado para el proceso. se realizarón los siguientes pasos:
1. Se creo un nuevo proceso, guardando datos en la seccion de "Informacion General".
2. Luego se creo un monitoreo para ese proceso.
3. Luego se guardo infromacion en la primera jornada de cada uno de los puntos.
4. Me sali de esta seccion y cargue una patalla del modulo de Configuracion
5. Despues volví al modulo de procesos y consulte el proceso que habia creado. pero al ir a la seccion de Informe de caracterizacion/Informacion Tecnica el sistema no carga los puntos que se habian guardado antes.

PDTA:
![hallazgos1](https://cloud.githubusercontent.com/assets/13665879/9095630/f112809a-3b7d-11e5-8306-1390d1c4d0db.png)

El problema parece presentarse solo si ha ha guardado informacion en al menos una jornada para cada punto. si no se guarda informacion el si carga los puntos.

**Comment by luiscdz** [comment]
Problema en la conversión de fechas ocasionaba el error en procedimientos recién creados

**Comment by mausygarcia** [comment]
Hola,

No puede enviar el .War por que aún presenta inconsistencia este punto. Hice la prueba de validación con el nuevo .War y el resultado es el siguiente:

 

1.       Funciona bien cuando se crea un nuevo proceso.

2.       No funciona bien si consulto un proceso de los creados anteriormente. Lo que hice para este caso fue:

-          Busqué un proceso creado anteriormente (Proceso 161) y lo edite. Este proceso me lo mostraba sin información tanto en la parte de arriba de la sección de información técnica, como en la parte de las jornadas, motivo por el cual procedí a ingresarle datos en todos los campos de esa sección (Información Técnica) y le di guardar.  Después me Salí del proceso y me fui nuevamente a consultar el  proceso 161, pero al entrar en el proceso los datos que había guardado no quedaron.

-          También pude notar que ayer los consecutivos de los proceso quedaron en el 195 y el proceso que cree hoy lo generó con Código 201. Al parecer respeta el consecutivo en el mismo día, pero al día siguiente lo crea de manera aleatoria.

 

De: Luis Cardozo [mailto:notifications@github.com] 
Enviado el: miércoles, 05 de agosto de 2015 08:30 p.m.
Para: luiscdz/SCV
CC: mausygarcia
Asunto: Re: [SCV] Proceso/InformeCaracterizacion/InformacionTecnica (#1)

 

Problema en la conversión de fechas ocasionaba el error en procedimientos recién creados 

—
Reply to this email directly or view it on GitHub <https://github.com/luiscdz/SCV/issues/1#issuecomment-128201632> .  <https://github.com/notifications/beacon/ANCGV6-UkIAVDckrcRsKitO-GZuHA6zUks5okrAggaJpZM4FmUwW.gif> 



---
El software de antivirus Avast ha analizado este correo electrónico en busca de virus.
https://www.avast.com/antivirus
