### ISSUE TITLE
Actividades económicas – parámetros fisicoquímicos

### ISSUE THREAD

**Issue by mausygarcia** [luiscdz/SCV#2]
En la pantalla de “Actividades económicas – parámetros fisicoquímicos” cambiar el label de los campo  “Mayor o igual rango inicial” por “Igual a rango inicial” y el campo “Mayor o igual rango final” por “Igual a rango final”.

PDTA:
Se que es algo que no se habia solicitado antes. Por fa revisalo a ver si me puedes colaborar con el cambio....Gracias...

**Comment by luiscdz** [comment]
Realizado
